apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: tim33/gateway
        resources:
          limits:
            memory: "300Mi"
            cpu: "250m"
        env:
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pulse-monitoring-secret
              key: mongoPassword        
        - name: CONFIG_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: pulse-monitoring-config-map
              key: configServerHost
        ports:
        - containerPort: 9292     
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 9090
    targetPort: 9292

              
      
       
        
